# Generated by Django 3.0.5 on 2020-04-14 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('addon', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('path_download', models.CharField(max_length=500)),
                ('path_upload', models.CharField(max_length=500)),
                ('cars', models.CharField(max_length=700)),
                ('piste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acserver.Piste')),
            ],
        ),
    ]
