# Generated by Django 3.0.5 on 2020-04-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('folder_name', models.CharField(max_length=200)),
                ('addon', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('folder_name', models.CharField(max_length=200)),
                ('addon', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('path_download', models.CharField(max_length=500)),
                ('path_upload', models.CharField(max_length=500)),
                ('file_cfg', models.CharField(max_length=500)),
                ('file_entry_list', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=11)),
                ('name_cmd', models.CharField(max_length=16)),
                ('cars', models.ManyToManyField(to='acserver.Car')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acserver.Track')),
            ],
        ),
    ]
