# Generated by Django 3.0.5 on 2020-04-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='file_cfg',
            field=models.CharField(default='path', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='file_entry_list',
            field=models.CharField(default='path', max_length=500),
            preserve_default=False,
        ),
    ]
