# Generated by Django 3.0.5 on 2020-04-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acserver', '0002_auto_20200418_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.CharField(default='stoping', max_length=7),
            preserve_default=False,
        ),
    ]
