# Generated by Django 3.0.5 on 2020-04-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acserver', '0003_server_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='name_cmd',
            field=models.CharField(default='ac_nfd_debutant', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(max_length=11),
        ),
    ]
