# Generated by Django 3.0.5 on 2020-04-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acserver', '0004_auto_20200419_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='folder_name',
            field=models.CharField(default='track_folder', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='folder_name',
            field=models.CharField(default='car_folder', max_length=200),
            preserve_default=False,
        ),
    ]
