# Generated by Django 3.0.5 on 2020-08-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200815_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userac',
            name='token',
            field=models.CharField(max_length=24, null=True, unique=True),
        ),
    ]
